### ISSUE TITLE
Archive GridPath RA toolkit hourly renewable energy generation profiles

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#296]
For our open energy data minimum viable product, we are going to use the hourly wind and solar generation profiles which have already been compiled for the [GridPath Resource Adequacy Toolkit](https://gridlab.org/gridpathratoolkit/). That data is currently stashed in Google Drive, as zipfiles containing a number of CSVs. The link above can be used to access the data in Google Drive.

This will be a one time manual archive that stands in for a more comprehensive way of producing these hourly profiles which will cover more time and the whole country instead of just WECC.  The files we want include:

- `MonteCarlo_Inputs/temporal_data/solar/*`
- `MonteCarlo_Inputs/temporal_data/solar_syn/*`
- `MonteCarlo_Inputs/temporal_data/wind/*`
- `MonteCarlo_Inputs/temporal_data/wind_syn/*`
- `TemporalData/DailyWeatherData_cleaned.csv`
- `TemporalData/HourlySolar_byProject/*`
- `TemporalData/HourlyWind_byProject/*`

In addition, Elaine Hart provided two additional CSVs which define how the individual plant/generator series for wind/solar are aggregated by BA or transmission zone:

- `solar-generator-aggregations.csv`
- `wind-plant-aggregations.csv`

All of these files should be archived and distributed with a `CC-BY-4.0` license.

```[tasklist]
### Tasks
- [x] Manually compile a `datapackage.json` for this data source
- [x] Create a Zenodo sandbox archive for testing
- [x] Add Zenodo sandbox DOI and dataset metadata to PUDL
- [x] Test that all `gridpathratk` data can be downloaded with `pudl_datastore`
- [x] Test that the `gridpathratk` archive can be verified by `pudl_datastore` successfully
- [x] Test that all `gridpathratk` source files can be accessed using the datastore module
- [x] Create a production Zenodo archive and switch to production DOI to PUDL
```

**Comment by zaneselvans** [comment]
After creating the sandbox archive and adding the DOI and source metadata to PUDL, I've tried to download a bit of data using:

```console
pudl_datastore --dataset gridpathratk -p part=daily-weather
```

The `datapackage.json` file is successfully downloaded, but the actual data file results in a broken connection:

<details>

<summary>✨Stack Trace✨</summary>

```
Traceback (most recent call last):
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.zenodo.com', port=443): Max retries exceeded with url: /records/38499/files/daily-weather.csv (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zane/miniforge3/envs/pudl-dev/bin/pudl_datastore", line 8, in <module>
    sys.exit(pudl_datastore())
             ^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 648, in pudl_datastore
    fetch_resources(
  File "/Users/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 487, in fetch_resources
    for res, contents in dstore.get_resources(
  File "/Users/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 395, in get_resources
    contents = self._zenodo_fetcher.get_resource(res)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 294, in get_resource
    content = self._fetch_from_url(url).content
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/code/catalyst/pudl/src/pudl/workspace/datastore.py", line 266, in _fetch_from_url
    response = self.http.get(url, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zane/miniforge3/envs/pudl-dev/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.zenodo.com', port=443): Max retries exceeded with url: /records/38499/files/daily-weather.csv (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
[1]    90483 exit 1     pudl_datastore --dataset gridpathratk -p part=daily-weather
```
</details>

I have been able to download the file directly from the URL in `datapackage.json`, but only once per IP address, and only through my browser, not via `wget`: https://sandbox.zenodo.com/records/38499/files/daily-weather.csv

**Comment by e-belfer** [comment]
@zaneselvans Looks like the entire sandbox.zenodo.com website is down right now, at least for me! I have never seen this error before but I'd assume that's the cause.

**Comment by zaneselvans** [comment]
Lol, thank you for finding the com vs. org.  This is an entirely manual archive (there's no archiver) whiiiiich is how the URL got screwed up.  I'll create a new version!
