### ISSUE TITLE
Automatically create archive approval checklist

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl-archiver#346]
### Overview

Filling out the archive approval checklist issue is tedious and seems automatable. Let's prioritize a small number of changes to make this quicker and less painful.

### Success Criteria
* [x] monthly archiving action automatically creates a new archive approval checklist issue
* [ ] monthly archive action populates the issue based on observed failures (including non-validation failures). stretch: the template is re-formatted based on the information (e.g., failed runs go into the failed run section). lower-hanging fruit goal is to add the updated slack template information as a comment on the issue.
* [ ] monthly archive action includes the highest priority information in the issue, to avoid having to open a million run summary JSONs. This includes: file changes (create/update/delete), size of file change in MB and percentage, change in partitions, and any validation failures.

### Current challenges
- We don't see any run failures in our existing automated reporting
- We only report run summaries report to Slack, not GH
- We don't show the size of changes in any of our reports, which makes assessing the scale of changes difficult.
