### ISSUE TITLE
Improve archivers and automated workflow to support faster data integration

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl-archiver#372]
In order to meet new deadlines for archiver creation and integration, we need to make several changes on the archiver side to enable quick automatic detection of new data archives.

- [x] Set up a daily archiver to check for early release (June, July) and final release data (Sept, Oct) for EIA 860, 861 and 923 data #373 and #374
- [x] Remove hard-coded year from NREL ATB archiver #377 
- [x] Remove hard-coded year from EIA 176 archiver #377

**Comment by e-belfer** [comment]
Created new issue for AEO archiver, which will not be necessary to address until 2025. As such, closing this issue.
