### ISSUE TITLE
update the EIA 176 archiver to get 2023

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl-archiver#484]
```[tasklist]
### Tasks
- [x] check in w/ ella about the archiver
- [x] make sure we are grabbing the 2023 data
- [x] make a draft archive
- [x] make a final archive
```

Periodically check [this link](https://www.eia.gov/naturalgas/ngqs/#?report=RP2&year1=2019&year2=2022&company=Name) for the released data.

**Comment by zaneselvans** [comment]
We're definitely not grabbing it now, and I just checked to see if the EIA-176 2023 data was available yet, and weirdly it seemed not to be (at least, not via the same URLs that are used for the 2022 data).

Would it make sense to automatically check for one year beyond whatever is in the current expected to be working years for the dataset, and if it's available archive it with a note to update the metadata for the data source?

**Comment by cmgosnell** [comment]
current status update: we are still waiting for EIA to publish the new data.

It appears our scraper is still working as intended. Despite some of the natural gas being updated with 2023 data, 176 has not yet been updated. The easiest place to double check is [here](https://www.eia.gov/naturalgas/ngqs/data/report). There are several nat gas datasets in there but the top one is one of the 176 tables.

**Comment by cmgosnell** [comment]
done: https://zenodo.org/records/14589676
