### ISSUE TITLE
Refresh Zenodo Archives Manually

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl-archiver#79]
The new archivers are working, but we don't have the infrastructure set up to run them on an automated schedule.  Instead up them manually, adding new archive lineages for the new datasets

- 🆕 New Dataset
- ✅ Updated Existing Archive
- ⛔ No Update
- 💀 Archiver is broken

```[tasklist]
- [x] ⛔ [Census DP1](https://zenodo.org/record/4127049)
- [x] 🆕 [EIA-176](https://zenodo.org/record/7682358) (See #80)
- [x] ⛔ [EIA-860](https://zenodo.org/record/7113854)
- [x] ✅ [EIA-860M](https://zenodo.org/record/7682381)
- [x] ✅ [EIA-923](https://zenodo.org/record/7682417)
- [x] ✅ [EIA Bulk Electricity](https://zenodo.org/record/7682482)
- [x] 🆕 [EIA Water](https://zenodo.org/record/7683136) (See #77, #80) 
- [x] ⛔ [EPA CAMD EIA Crosswalk](https://zenodo.org/record/7650939)
- [x] 💀 [EPA CEMS](https://zenodo.org/record/6910058) (See #68)
- [x] ⛔ FERC-1 (Skipped due to #73)
- [x] ⛔ FERC-2 (Skipped due to #73)
- [x] ⛔ FERC-6 (Skipped due to #73)
- [x] ⛔ FERC-60 (Skipped due to #73)
- [x] ⛔ FERC-714 (Skipped due to #73)
- [x] 💀 FERC EQR (See #31, #43, #44)
- [x] 🆕 [MSHA Mines](https://doi.org/10.5281/zenodo.7683517) (Lots of up & download errors. See #80, #81)
- [x] 🆕 [PHMSA Natural Gas](https://zenodo.org/record/7683352) (See #80)
```
